ccflags-y += -I$(srctree)/drivers/kernelsu
ccflags-y += -I$(srctree)/drivers/kernelsu/core
ccflags-y += -I$(srctree)/drivers/kernelsu/policy
subdir-ccflags-y += -I$(srctree)/drivers/kernelsu
subdir-ccflags-y += -I$(srctree)/drivers/kernelsu/core
subdir-ccflags-y += -I$(srctree)/drivers/kernelsu/policy

obj-y += core/
obj-y += policy/
